name: Upload Python Package

on:
  push:
    tags:
      - "*" # Will trigger for every tag, alternative: 'v*'

permissions:
  # This permission is needed for private repositories.
  contents: read
  # This permission is mandatory for trusted publishing to PyPi.
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: |
          pdm --version
          pdm install

      - name: Build and publish
        run: |
          pdm publish